services:
  init:
    env_file:
      - .env
    image: smanx/opencode:1.18.23
    volumes:
      - data:/workspace
    entrypoint: []
    command: sh -c "cd /workspace; [ -d "git-automate-e2e" ] || git clone https://github.com/krampenschiesser/git-automate-e2e"
  opencode:
    depends_on:
      init:
        condition: service_completed_successfully
    env_file: .env
    image: smanx/opencode:1.18.23
    ports:
      - "10082:4096"
    environment:
      -OPENCODE_LOG_LEVEL: DEBUG
      -OPENCODE_PRINT_LOGS: true
    volumes:
      - "./docker/opencode-cfg.json:/root/.config/opencode/opencode.json"
      - data:/workspace
      - opencode-logs:/root/.local/share/opencode/logs
  opencode-logs:
    depends_on:
      opencode:
        condition: service_started
    image: smanx/opencode:1.18.23
    volumes:
      - opencode-logs:/root/.local/share/opencode/logs
      - data:/workspace
    entrypoint: []
    command: tail -f /root/.local/share/opencode/logs/log/*
volumes:
  data:
  opencode-logs: