query ListPrComments($owner: String!, $repo: String!, $prNumber: Int!) {
    repository(owner: $owner, name: $repo) {
        pullRequest(number: $prNumber) {
            comments(first: 100) {
                nodes {
                    id
                    body
                    createdAt
                    author {
                        ... on User { login }
                        ... on Bot { login }
                        ... on Organization { login }
                    }
                }
            }
        }
    }
}
