query RepositoryProjectIssues($owner: String!, $name: String!) {
    repository(owner: $owner, name: $name) {
        issues(first: 10) {
            edges {
                node {
                    number,
                    id,
                    title,
                    body,
                    state,
                    projectItems(first: 10) {
                        edges {
                            node {
                                project {
                                    id,number,title
                                }
                                sessionId: fieldValueByName(name: "SessionId") {

                                    ... on ProjectV2ItemFieldTextValue{
                                        text
                                    }
                                },
                                status: fieldValueByName(name: "Status") {

                                    ... on ProjectV2ItemFieldSingleSelectValue{
                                        name,
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
query PullRequestsFromAi($owner: String!, $name: String!) {
    repository(owner: $owner, name: $name) {
        pullRequests(first: 10) {
            edges {
                node {
                    id,
                    number

                    closingIssuesReferences(first: 10) {
                        edges {
                            node {
                                id
                                title
                                number
                            }
                        }
                    }
                }
            }
        }
    }

}
query PullRequestReviews($owner: String!, $name: String!, $pullRequest: Int!) {
    repository(name: $name, owner: $owner) {
        pullRequest(number: $pullRequest) {
            title,
            id,
            number,
            reviews(first: 10) {
                edges {
                    node {
                        id,
                        body,
                        comments(first: 100) {
                            edges {
                                node {
                                    id,
                                    body,
                                    originalLine,
                                    path,
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

query PullRequestReviews($owner: String!, $name: String!) {
    repository(owner: $owner, name: $name) {
        pullRequests(first: 10) {
            edges {
                node {
                    title,
                    id,
                    number
                    reviews(first: 10) {
                        edges {
                            node {
                                id,
                                body,
                                comments(first: 100) {
                                    edges {
                                        node {
                                            id,
                                            body,
                                            originalLine,
                                            path,
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
